### ISSUE TITLE
v1.6 breaks app: does launch but doesn’t work on macOS Big Sur

### ISSUE THREAD

**Issue by philihub** [dwarvesf/hidden#92] opened 2020-08-25 09:09 UTC
I know, I know, Big Sur is a public beta but before the 1.6 update Hidden Bar working totally fine 👍

**Comment by al-wi** [comment] 2020-08-28 05:40
Are you sure that it is only Big Sur? 
Since updating to 1.6 it also stopped working on Catalina 10.15.6.

Basically it launches and is visible in the bar. However, it is not possible to hide the icons clicking on ">".

**Comment by philihub** [comment] 2020-08-28 06:21
I did not say that 😉 On my machine, where I run Big Sur, it doesn’t work after the update as you also described.

**Comment by phucledien** [comment] 2020-08-28 10:37
Hi guys,

sorry but I cannot reproduce the bug. The latest version of hidden bar works perfectly on my machine (Big Sur beta 5)

**Comment by philihub** [comment] 2020-08-28 10:43
Hm, I quit and restarted and it is now working. I did restart it a few times already and it did to work.

**Comment by al-wi** [comment] 2020-08-29 19:26
I can confirm that it is not related to version 1.6. Even installing 1.5 didn't solve the issue for me.
Removing the App including all config files (e.g. with AppCleaner) and reinstalling it helped me.

**Comment by dnivi3** [comment] 2020-12-05 13:10
I'm having the same problem. Am on a M1 (ARM) Mac, so that may also cause the problem?

**Comment by viettrungphan** [comment] 2021-03-03 03:40
Fixed on latest MacOS

**Closed by viettrungphan** 2021-03-03 03:40 UTC
