### ISSUE TITLE
Remove dock icon after closing the app window

### ISSUE THREAD

**Issue by muli** [dwarvesf/hidden#27] opened 2019-12-15 10:50 UTC
### Describe the bug

When closing the preferences window (by either clicking the 'x' icon or cmd+w), the dock icon should be removed.

### Steps to reproduce

1. Open the app's preferences window.
2. Close it (not quit) by clicking the 'x' icon on the top or by pressing cmd+w.

### Expected behaviour

While the app is running in the background - the icon should not be in the dock and take space.

### Environment
**Desktop (please complete the following information):**
 - OS: macOS Catalina.
 - Version 1.15.1.

**Comment by phucledien** [comment] 2019-12-16 07:11
Hi @muli, you can deselect the option: keep the icon in dock in the preference window, so the dock icon will be hidden
![image](https://user-images.githubusercontent.com/14150687/70886370-f11b8e00-200d-11ea-99b8-9b7ae57bb594.png)

**Comment by muli** [comment] 2019-12-16 07:26
Hi @phucledien,

Thanks for your reply.

Firstly, I somehow missed that setting, so thanks for pointing it out. This solves my issue.

I will say, though, that normally applications that have a preference window -- when the preferences window is open, the dock icon is visible and disappears when you close this window.

But hiding the icon altogether is fine by me.

**Comment by phucledien** [comment] 2019-12-16 07:37
ok cool! btw thanks for your issue @muli, we maybe change this behavior in the next release. 
I will close this issue because the problem is resolved 👍

**Closed by phucledien** 2019-12-16 07:37 UTC
